#!/usr/bin/env python3
"""Generate a function-entry tracer for ranges of recompiled guest functions.

    python3 tools/gen_function_trace.py OUT.cpp 823E0000-823F4000 [823AD000-823B4000 ...]

Every generated function in the ranges gets an override that logs its first
three calls, then runs the original. Functions src/native already overrides
are skipped. Build it in with -DTABLETENNIS_FUNCTION_TRACE_SOURCE=OUT.cpp;
debugging only.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    ranges = [tuple(int(part, 16) for part in spec.split("-")) for spec in sys.argv[2:]]
    defined = set()
    for path in (ROOT / "generated/default").glob("tabletennis_recomp.*.cpp"):
        defined.update(int(name, 16) for name in
                       re.findall(r"^DEFINE_REX_FUNC\(sub_([0-9A-F]+)\)", path.read_text(), re.M))
    overridden = set()
    for path in (ROOT / "src/native").glob("*.cpp"):
        overridden.update(int(name, 16) for name in
                          re.findall(r"REX_FUNC\(sub_([0-9A-F]+)\)", path.read_text()))
    traced = sorted(address for address in defined - overridden
                    if any(low <= address < high for low, high in ranges))
    lines = [
        '#include "generated/default/tabletennis_init.h"',
        "",
        "#include <atomic>",
        "",
        "#include <rex/logging.h>",
        "",
        "// Generated by tools/gen_function_trace.py; debugging only.",
        "namespace {",
        f"std::atomic<uint32_t> calls[{len(traced)}];",
        "void Trace(uint32_t index, uint32_t address) {",
        "  if (calls[index].fetch_add(1, std::memory_order_relaxed) < 3) {",
        '    REXLOG_INFO("trace sub_{:08X}", address);',
        "  }",
        "}",
        "}  // namespace",
        "",
    ]
    for index, address in enumerate(traced):
        lines += [f"extern \"C\" REX_FUNC(sub_{address:08X}) {{",
                  f"  Trace({index}, 0x{address:08X});",
                  f"  __imp__sub_{address:08X}(ctx, base);",
                  "}"]
    Path(sys.argv[1]).write_text("\n".join(lines) + "\n")
    print(f"{len(traced)} functions traced into {sys.argv[1]}")


if __name__ == "__main__":
    main()
