#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shaderDirectory = join(root, "src/native/shaders");
const shader = join(shaderDirectory, "tabletennis_crowd_observer.hlsl");
const output = join(
  shaderDirectory,
  "tabletennis_crowd_observer_spirv.h",
);
const temporary = mkdtempSync(join(tmpdir(), "tt-crowd-spv-"));

function readDescriptorBindings(binary) {
  const disassembly = execFileSync("spirv-dis", [binary], {
    encoding: "utf8",
  });
  const names = new Map();
  const descriptors = new Map();
  for (const line of disassembly.split("\n")) {
    const name = line.match(/OpName %(\S+) "([^"]+)"/);
    if (name !== null) {
      names.set(name[1], name[2]);
      continue;
    }
    const decoration = line.match(
      /OpDecorate %(\S+) (DescriptorSet|Binding) (\d+)/,
    );
    if (decoration === null) {
      continue;
    }
    const descriptor = descriptors.get(decoration[1]) ?? {};
    descriptor[decoration[2]] = Number(decoration[3]);
    descriptors.set(decoration[1], descriptor);
  }
  return { names, descriptors };
}

function assertDescriptorBindings(stage, binary) {
  const { names, descriptors } = readDescriptorBindings(binary);
  const expected =
    stage === "vert"
      ? new Map([
          ["crowd_vertex_words", { DescriptorSet: 0, Binding: 1 }],
          [
            "crowd_palette_word_pairs",
            { DescriptorSet: 0, Binding: 2 },
          ],
        ])
      : new Map([
          ["crowd_texture", { DescriptorSet: 1, Binding: 0 }],
          ["crowd_sampler", { DescriptorSet: 0, Binding: 3 }],
        ]);

  for (const [resourceName, wanted] of expected) {
    const actual = [...names]
      .filter(([, name]) => name === resourceName)
      .map(([id]) => descriptors.get(id))
      .find((descriptor) => descriptor !== undefined);
    if (
      actual?.DescriptorSet !== wanted.DescriptorSet ||
      actual?.Binding !== wanted.Binding
    ) {
      throw new Error(
        `${stage}: ${resourceName} descriptor is ` +
          `${actual?.DescriptorSet ?? "missing"}/` +
          `${actual?.Binding ?? "missing"}, expected ` +
          `${wanted.DescriptorSet}/${wanted.Binding}`,
      );
    }
  }

  if (stage === "vert") {
    const hasConstants = [...descriptors.values()].some(
      (descriptor) =>
        descriptor.DescriptorSet === 0 && descriptor.Binding === 0,
    );
    if (!hasConstants) {
      throw new Error(`${stage}: constants are not set 0 binding 0`);
    }
  }
}

function compile(stage, entry) {
  const binary = join(temporary, `${entry}.spv`);
  execFileSync(
    "glslangValidator",
    [
      "-D",
      "--D",
      "TABLETENNIS_VULKAN=1",
      "-V",
      "--target-env",
      "vulkan1.1",
      "-Os",
      "-S",
      stage,
      "-e",
      entry,
      "-o",
      binary,
      shader,
    ],
    { stdio: "inherit" },
  );
  execFileSync("spirv-val", ["--target-env", "vulkan1.1", binary], {
    stdio: "inherit",
  });
  assertDescriptorBindings(stage, binary);
  return readFileSync(binary);
}

function words(name, binary) {
  if (binary.length % 4 !== 0) {
    throw new Error(`${name}: SPIR-V byte count is not word-aligned`);
  }
  const values = [];
  for (let offset = 0; offset < binary.length; offset += 4) {
    values.push(
      `0x${binary.readUInt32LE(offset).toString(16).padStart(8, "0")}`,
    );
  }
  const lines = [];
  for (let index = 0; index < values.length; index += 8) {
    lines.push(`    ${values.slice(index, index + 8).join(", ")},`);
  }
  return (
    `inline constexpr uint32_t ${name}[] = {\n` +
    `${lines.join("\n")}\n};\n`
  );
}

try {
  const vertex = compile("vert", "vs_main");
  const pixel = compile("frag", "ps_main");
  const source = readFileSync(shader, "utf8");
  if (source.includes(")tt_hlsl\"")) {
    throw new Error("shader source collides with raw-string delimiter");
  }
  const generated =
    `// Generated by tools/generate_crowd_observer_spirv.mjs.\n` +
    `// DO NOT EDIT. Regenerate after changing the HLSL source.\n` +
    `#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n` +
    `namespace tabletennis::native::crowd_observer_shader {\n\n` +
    `inline constexpr char kHlsl[] = R"tt_hlsl(\n` +
    `${source})tt_hlsl";\n\n` +
    `${words("kVertexSpirv", vertex)}` +
    `inline constexpr size_t kVertexSpirvBytes = ` +
    `sizeof(kVertexSpirv);\n\n` +
    `${words("kPixelSpirv", pixel)}` +
    `inline constexpr size_t kPixelSpirvBytes = ` +
    `sizeof(kPixelSpirv);\n\n` +
    `}  // namespace tabletennis::native::crowd_observer_shader\n`;
  writeFileSync(output, generated);
  process.stdout.write(`wrote ${output}\n`);
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
