#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shader = join(
  root,
  "src/native/shaders/tabletennis_observer_overlay.hlsl",
);
const output = join(
  root,
  "src/native/shaders/tabletennis_observer_overlay_spirv.h",
);
const temporary = mkdtempSync(join(tmpdir(), "tt-overlay-spv-"));

function readDescriptorBindings(binary) {
  const disassembly = execFileSync("spirv-dis", [binary], {
    encoding: "utf8",
  });
  const names = new Map();
  const descriptors = new Map();
  for (const line of disassembly.split("\n")) {
    const name = line.match(/OpName %(\S+) "([^"]+)"/);
    if (name !== null) {
      names.set(name[1], name[2]);
      continue;
    }
    const decoration = line.match(
      /OpDecorate %(\S+) (DescriptorSet|Binding) (\d+)/,
    );
    if (decoration === null) {
      continue;
    }
    const descriptor = descriptors.get(decoration[1]) ?? {};
    descriptor[decoration[2]] = Number(decoration[3]);
    descriptors.set(decoration[1], descriptor);
  }
  return { names, descriptors };
}

function assertDescriptorBindings(stage, binary) {
  const { names, descriptors } = readDescriptorBindings(binary);
  const expected =
    stage === "frag"
      ? new Map([
          ["base_texture", { DescriptorSet: 1, Binding: 0 }],
          ["detail_texture", { DescriptorSet: 1, Binding: 1 }],
          ["base_sampler", { DescriptorSet: 0, Binding: 1 }],
          ["detail_sampler", { DescriptorSet: 0, Binding: 2 }],
        ])
      : new Map();

  for (const [resourceName, expectedDescriptor] of expected) {
    const resourceId = [...names].find(([, name]) => name === resourceName)?.[0];
    const actual = resourceId === undefined
      ? undefined
      : descriptors.get(resourceId);
    if (
      actual?.DescriptorSet !== expectedDescriptor.DescriptorSet ||
      actual?.Binding !== expectedDescriptor.Binding
    ) {
      throw new Error(
        `${stage}: ${resourceName} descriptor is ` +
          `${actual?.DescriptorSet ?? "missing"}/` +
          `${actual?.Binding ?? "missing"}, expected ` +
          `${expectedDescriptor.DescriptorSet}/${expectedDescriptor.Binding}`,
      );
    }
  }

  const hasConstants = [...descriptors.values()].some(
    (descriptor) =>
      descriptor.DescriptorSet === 0 && descriptor.Binding === 0,
  );
  if (!hasConstants) {
    throw new Error(`${stage}: constants are not mapped to set 0 binding 0`);
  }
}

function compile(stage, entry) {
  const binary = join(temporary, `${entry}.spv`);
  execFileSync(
    "glslangValidator",
    [
      "-D",
      "--D",
      "TABLETENNIS_VULKAN=1",
      "-V",
      "--target-env",
      "vulkan1.1",
      "-Os",
      "-S",
      stage,
      "-e",
      entry,
      "-o",
      binary,
      shader,
    ],
    { stdio: "inherit" },
  );
  assertDescriptorBindings(stage, binary);
  return readFileSync(binary);
}

function words(name, binary) {
  if (binary.length % 4 !== 0) {
    throw new Error(`${name}: SPIR-V byte count is not word-aligned`);
  }
  const values = [];
  for (let offset = 0; offset < binary.length; offset += 4) {
    values.push(`0x${binary.readUInt32LE(offset).toString(16).padStart(8, "0")}`);
  }
  const lines = [];
  for (let index = 0; index < values.length; index += 8) {
    lines.push(`    ${values.slice(index, index + 8).join(", ")},`);
  }
  return `inline constexpr uint32_t ${name}[] = {\n${lines.join("\n")}\n};\n`;
}

try {
  const source = readFileSync(shader, "utf8");
  if (source.includes(")tt_hlsl\"")) {
    throw new Error("HLSL source collides with generated raw-string delimiter");
  }
  const vertex = compile("vert", "vs_main");
  const pixel = compile("frag", "ps_main");
  const generated = `// Generated by tools/generate_observer_overlay_spirv.mjs.
// DO NOT EDIT. Regenerate after changing tabletennis_observer_overlay.hlsl.
#pragma once

#include <cstddef>
#include <cstdint>

namespace tabletennis::native::overlay_shader {

inline constexpr char kHlsl[] = R"tt_hlsl(
${source})tt_hlsl";

${words("kVertexSpirv", vertex)}
inline constexpr size_t kVertexSpirvBytes = sizeof(kVertexSpirv);

${words("kPixelSpirv", pixel)}
inline constexpr size_t kPixelSpirvBytes = sizeof(kPixelSpirv);

}  // namespace tabletennis::native::overlay_shader
`;
  writeFileSync(output, generated);
  process.stdout.write(`wrote ${output}\n`);
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
