#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shaderDirectory = join(root, "src/native/shaders");
const shader = join(
  shaderDirectory,
  "tabletennis_player_motion_composite.hlsl",
);
const output = join(
  shaderDirectory,
  "tabletennis_player_motion_composite_spirv.h",
);
const temporary = mkdtempSync(join(tmpdir(), "tt-player-motion-spv-"));

function findNamedId(disassembly, name) {
  const match = disassembly.match(
    new RegExp(`OpName %(\\S+) "${name}"`),
  );
  if (match === null) {
    throw new Error(`SPIR-V resource ${name} is missing`);
  }
  return match[1];
}

function assertDecoration(disassembly, id, decoration, value) {
  if (
    !new RegExp(
      `OpDecorate %${id} ${decoration} ${value}`,
    ).test(disassembly)
  ) {
    throw new Error(
      `SPIR-V resource %${id} is not ${decoration} ${value}`,
    );
  }
}

function assertDescriptorExists(disassembly, descriptorSet, binding) {
  const decoratedIds = [
    ...disassembly.matchAll(
      new RegExp(
        `OpDecorate %(\\S+) DescriptorSet ${descriptorSet}`,
        "g",
      ),
    ),
  ].map((match) => match[1]);
  if (
    !decoratedIds.some((id) =>
      new RegExp(`OpDecorate %${id} Binding ${binding}`).test(
        disassembly,
      ),
    )
  ) {
    throw new Error(
      `SPIR-V has no descriptor at set ${descriptorSet} binding ${binding}`,
    );
  }
}

function assertBindings(binary) {
  const disassembly = execFileSync("spirv-dis", [binary], {
    encoding: "utf8",
  });
  const texture = findNamedId(disassembly, "player_motion_scene");
  const sampler = findNamedId(disassembly, "player_motion_sampler");
  // glslang leaves the cbuffer variable anonymous and names only its block.
  assertDescriptorExists(disassembly, 0, 0);
  assertDecoration(disassembly, texture, "DescriptorSet", 1);
  assertDecoration(disassembly, texture, "Binding", 0);
  assertDecoration(disassembly, sampler, "DescriptorSet", 0);
  assertDecoration(disassembly, sampler, "Binding", 1);
}

function compile() {
  const binary = join(temporary, "ps_main.spv");
  execFileSync(
    "glslangValidator",
    [
      "-D",
      "--D",
      "TABLETENNIS_VULKAN=1",
      "-V",
      "--target-env",
      "vulkan1.1",
      "-Os",
      "-S",
      "frag",
      "-e",
      "ps_main",
      "-o",
      binary,
      shader,
    ],
    { stdio: "inherit" },
  );
  execFileSync("spirv-val", ["--target-env", "vulkan1.1", binary], {
    stdio: "inherit",
  });
  assertBindings(binary);
  return readFileSync(binary);
}

function words(name, binary) {
  if (binary.length % 4 !== 0) {
    throw new Error(`${name}: SPIR-V byte count is not word-aligned`);
  }
  const values = [];
  for (let offset = 0; offset < binary.length; offset += 4) {
    values.push(
      `0x${binary.readUInt32LE(offset).toString(16).padStart(8, "0")}`,
    );
  }
  const lines = [];
  for (let index = 0; index < values.length; index += 8) {
    lines.push(`    ${values.slice(index, index + 8).join(", ")},`);
  }
  return (
    `inline constexpr uint32_t ${name}[] = {\n` +
    `${lines.join("\n")}\n};\n`
  );
}

try {
  const pixel = compile();
  const source = readFileSync(shader, "utf8");
  if (source.includes(")tt_hlsl\"")) {
    throw new Error("shader source collides with raw-string delimiter");
  }
  const generated =
    `// Generated by tools/generate_player_motion_composite_spirv.mjs.\n` +
    `// DO NOT EDIT. Regenerate after changing the HLSL source.\n` +
    `#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n` +
    `namespace tabletennis::native::player_motion_composite_shader {\n\n` +
    `inline constexpr char kHlsl[] = R"tt_hlsl(\n` +
    `${source})tt_hlsl";\n\n` +
    `${words("kPixelSpirv", pixel)}` +
    `inline constexpr size_t kPixelSpirvBytes = ` +
    `sizeof(kPixelSpirv);\n\n` +
    `}  // namespace tabletennis::native::player_motion_composite_shader\n`;
  writeFileSync(output, generated);
  process.stdout.write(`wrote ${output}\n`);
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
