#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import {
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shaderDirectory = join(root, "src/native/shaders");
const shader = join(
  shaderDirectory,
  "tabletennis_native_scene_resolve.hlsl",
);
const output = join(
  shaderDirectory,
  "tabletennis_native_scene_resolve_spirv.h",
);
const temporary = mkdtempSync(join(tmpdir(), "tt-scene-resolve-spv-"));

function assertResolveBinding(binary) {
  const disassembly = execFileSync("spirv-dis", [binary], {
    encoding: "utf8",
  });
  const resource = disassembly.match(
    /OpName %(\S+) "native_scene_msaa_color"/,
  );
  if (
    resource === null ||
    !new RegExp(
      `OpDecorate %${resource[1]} DescriptorSet 1`,
    ).test(disassembly) ||
    !new RegExp(`OpDecorate %${resource[1]} Binding 0`).test(
      disassembly,
    )
  ) {
    throw new Error(
      "native_scene_msaa_color is not set 1 binding 0",
    );
  }
}

function compile(stage, entry) {
  const binary = join(temporary, `${entry}.spv`);
  execFileSync(
    "glslangValidator",
    [
      "-D",
      "--D",
      "TABLETENNIS_VULKAN=1",
      "-V",
      "--target-env",
      "vulkan1.1",
      "-Os",
      "-S",
      stage,
      "-e",
      entry,
      "-o",
      binary,
      shader,
    ],
    { stdio: "inherit" },
  );
  execFileSync("spirv-val", ["--target-env", "vulkan1.1", binary], {
    stdio: "inherit",
  });
  if (stage === "frag") {
    assertResolveBinding(binary);
  }
  return readFileSync(binary);
}

function words(name, binary) {
  if (binary.length % 4 !== 0) {
    throw new Error(`${name}: SPIR-V byte count is not word-aligned`);
  }
  const values = [];
  for (let offset = 0; offset < binary.length; offset += 4) {
    values.push(
      `0x${binary.readUInt32LE(offset).toString(16).padStart(8, "0")}`,
    );
  }
  const lines = [];
  for (let index = 0; index < values.length; index += 8) {
    lines.push(`    ${values.slice(index, index + 8).join(", ")},`);
  }
  return (
    `inline constexpr uint32_t ${name}[] = {\n` +
    `${lines.join("\n")}\n};\n`
  );
}

try {
  const vertex = compile("vert", "vs_main");
  const pixel = compile("frag", "ps_main");
  const source = readFileSync(shader, "utf8");
  if (source.includes(")tt_hlsl\"")) {
    throw new Error("shader source collides with raw-string delimiter");
  }
  const generated =
    `// Generated by tools/generate_native_scene_resolve_spirv.mjs.\n` +
    `// DO NOT EDIT. Regenerate after changing the HLSL source.\n` +
    `#pragma once\n\n#include <cstddef>\n#include <cstdint>\n\n` +
    `namespace tabletennis::native::native_scene_resolve_shader {\n\n` +
    `inline constexpr char kHlsl[] = R"tt_hlsl(\n` +
    `${source})tt_hlsl";\n\n` +
    `${words("kVertexSpirv", vertex)}` +
    `inline constexpr size_t kVertexSpirvBytes = ` +
    `sizeof(kVertexSpirv);\n\n` +
    `${words("kPixelSpirv", pixel)}` +
    `inline constexpr size_t kPixelSpirvBytes = ` +
    `sizeof(kPixelSpirv);\n\n` +
    `}  // namespace tabletennis::native::native_scene_resolve_shader\n`;
  writeFileSync(output, generated);
  process.stdout.write(`wrote ${output}\n`);
} finally {
  rmSync(temporary, { recursive: true, force: true });
}
